#10045 Packing instructions are no longer displayed when ordering
metasfresh/metasfresh pull request #10048
Opened 2020-10-01 10:21 UTC by cristinamghita

#10045 Packing instructions are no longer displayed when ordering

2020-10-01 14:13 UTC, teosarca commented on backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPIItemProductDAO.java
> +	private static final String SYSCONFIG_Enforce_M_HU_PI_Item_Product_ID = "de.metas.handlingunits.impl.HUPIItemProductDAO.Enforce_M_HU_PI_Item_Product_ID";
move this sysconfig to de.metas.ui.web.quickinput.field.PackingItemProductFieldHelper and call it `de.metas.ui.web.quickinput.field.PackingItemProductFieldHelper.EnforcePrecisePricePerHUItemProduct`.

2020-10-01 14:14 UTC, teosarca commented on backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/impl/HUPIItemProductDAO.java
> +			if (enforceHU_PI_Item_Product && queryVO.getPriceListVersionId() != null)
do this checking in de.metas.ui.web.quickinput.field.PackingItemProductFieldHelper and decide there if u set queryVO's priceListVersionId.

2020-10-01 14:14 UTC, teosarca requested changes
check my comments

2020-10-01 14:20 UTC, teosarca commented on backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5569170_sys_gh10045_AddSysConfig.sql
> +INSERT INTO AD_SysConfig (AD_Client_ID,AD_Org_ID,AD_SysConfig_ID,ConfigurationLevel,Created,CreatedBy,EntityType,IsActive,Name,Updated,UpdatedBy,Value) VALUES (0,0,541342,'C',TO_TIMESTAMP('2020-10-01
rename it to `de.metas.ui.web.quickinput.field.PackingItemProductFieldHelper.EnforcePrecisePricePerHUItemProduct`

2020-10-01 14:20 UTC, teosarca commented on backend/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/system/70-de.metas.fresh/5569170_sys_gh10045_AddSysConfig.sql
> +UPDATE AD_SysConfig SET Name='de.metas.handlingunits.impl.HUPIItemProductDAO.Enforce_M_HU_PI_Item_Product_ID',Updated=TO_TIMESTAMP('2020-10-01 13:34:07','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE A
rename it to `de.metas.ui.web.quickinput.field.PackingItemProductFieldHelper.EnforcePrecisePricePerHUItemProduct`

2020-10-06 07:52 UTC, cristinamghita commented on backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/quickinput/field/PackingItemProductFieldHelper.java
> +		final boolean enforcePrecisePricePerHUItemProduct = sysConfigBL.getBooleanValue(SYSCONFIG_EnforcePrecisePricePerHUItemProduct, false);
Agree. Tested and fixed it! Thx!

2020-10-06 09:34 UTC, merged