Gh6310 new service handling units window
metasfresh/metasfresh pull request #10346
Opened 2020-12-03 09:56 UTC by BodorAnnamaria

2020-12-03 12:44 UTC, metas-ts requested changes

2020-12-03 12:44 UTC, metas-ts commented on backend/metasfresh-webui-api/src/main/java/de/metas/ui/web/handlingunits/HUEditorViewFactoryTemplate.java
> +		//When the Factory is ServiceHUEditorViewFactory always need to execute the customizeViewLayout method, is not configuration dependent
* please make the method `protected and override it in `ServiceHUEditorViewFactory`
* add the comment "When the Factory is ServiceHUEditorViewFactory always need to execute the customizeViewLayout method, is not configuration dependent" 
to the overriding method as a javadoc
* (it's cleaner)

2020-12-03 13:11 UTC, metas-ts approved these changes

2020-12-03 13:15 UTC, merged

2020-12-11 09:45 UTC, cristinamghita commented
Linked to https://github.com/metasfresh/metasfresh/issues/10414