gh10448
metasfresh/metasfresh pull request #10452
Opened 2020-12-16 14:34 UTC by adi-stefan

https://github.com/metasfresh/metasfresh/issues/10448

2020-12-18 10:09 UTC, metas-ts requested changes
please check my comments. i think the biggest chunk still to do is that cache-thingie

2020-12-18 10:09 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/bpartner/composite/repository/BPartnerCompositeSaver.java
> +		if (!Check.isEmpty(bpartner.getInvoiceRule()))
```suggestion
		if (bpartner.getInvoiceRule() != null)
```

i know we do have that method, but as the Invoicerule can be just null or nut-null (unlike a String or List), i think the code is clearer like this

2020-12-18 10:15 UTC, adi-stefan commented on backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/invoicecandidate/internalbusinesslogic/InvoiceCandidate.java
> -				if (product.isStocked())
That logic was duplicated below, on the CustomerScheduleAfterDelivery branch of the case

2020-12-21 14:49 UTC, metas-ts approved these changes

2020-12-21 15:14 UTC, merged