Master product api
metasfresh/metasfresh pull request #10827
Opened 2021-03-17 07:36 UTC by cp-ps

2021-03-17 09:25 UTC, metas-ts requested changes

2021-03-17 09:25 UTC, metas-ts commented on backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/upsertProduct.feature
> +      | productIdentifier | ProductCode | Name         | Type | UOMCode | OPT.EAN  | OPT.GTIN  | OPT.Description  | OPT.isActive |
if these are json-properties, then use the exact property names like `uomCode`

2021-03-17 09:25 UTC, metas-ts commented on backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/upsertProduct.feature
> +    And the request is set in context of syncAdvise 'CREATE_OR_MERGE'
```suggestion
    And we create a JsonRequestProductUpsert, set syncAdvise to 'CREATE_OR_MERGE', add the JsonRequestProductUpsertItems and store it in the test context
```

2021-03-17 11:44 UTC, cif-ps commented on backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/upsertProduct.feature
> +    Given the user adds bpartner product
The external references are not parts of the payload, changed to "metasfresh contains S_ExternalReferences"

2021-03-18 06:27 UTC, metas-ts requested changes

2021-03-18 06:27 UTC, metas-ts commented on backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/product/ProductRestController.java
> +	@ApiOperation("Create or update products and corresponding Bpartner-products.")
please consolidate this class with `ProductsRestController` and add the API-Docu there.

2021-03-18 06:27 UTC, metas-ts commented on backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/v2/product/ProductRestController.java
> +	public ResponseEntity<JsonResponseUpsert> upsertProducts(@RequestBody @NonNull final JsonRequestProductUpsert request,
also add an `@ApiParam` (=> orientate on `BpartnerRelationRestController.retrieveBPartner()`)

2021-03-18 06:27 UTC, metas-ts commented on backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/RESTUtil.java
> +				if (EmptyUtil.isBlank(syncAdvise))
please avoid such deep nesting by moving this if-block to the start of the method

2021-03-18 06:27 UTC, metas-ts commented on backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/product/UpsertProduct_StepDef.java
> +			final IExternalReferenceType externalReferenceType = getExternalReferenceType(DataTableUtil.extractStringForColumnName(dataTableEntry, "ExternalReference.Code"));
```suggestion
			final IExternalReferenceType externalReferenceType = getExternalReferenceType(DataTableUtil.extractStringForColumnName(dataTableEntry, "ExternalReferenceType.Code"));
```

2021-03-18 08:16 UTC, metas-ts approved these changes

2021-03-18 08:16 UTC, merged