gh10841 - Purchase Candidate REST implementation
metasfresh/metasfresh pull request #10888
Opened 2021-03-25 11:04 UTC by adi-stefan

https://github.com/metasfresh/metasfresh/issues/10841

2021-03-25 14:04 UTC, metas-ts requested changes

2021-03-25 14:04 UTC, metas-ts commented on backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createPurchaseCandidate.feature
> +  Scenario: create a purchase candidate
```suggestion
```

2021-03-26 09:30 UTC, adi-stefan commented on backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/document/impl/DocumentLocationBL.java
> +			final I_M_Warehouse warehouse = Services.get(IWarehouseDAO.class).getById(WarehouseId.ofRepoId(warehouseId));
Extracted

2021-03-26 09:30 UTC, adi-stefan commented on backend/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/warehouse/api/impl/WarehouseBL.java
> +		final I_C_BPartner_Location bpLocation = Services.get(IBPartnerDAO.class).getBPartnerLocationById(BPartnerLocationId.ofRepoIdOrNull(warehouse.getC_BPartner_ID(),warehouse.getC_BPartner_Location_ID(
extracted

2021-03-26 09:30 UTC, adi-stefan commented on backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/order/impl/CreatePurchaseCandidatesService.java
> +package de.metas.rest_api.order.impl;
moved.

2021-03-26 09:31 UTC, adi-stefan commented on backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/order/impl/CreatePurchaseCandidatesService.java
> +				.discount(discount)
you're right, removed.

2021-03-26 09:31 UTC, adi-stefan commented on backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/order/impl/CreatePurchaseCandidatesService.java
> +	private ZonedDateTime getOrDefaultDatePromised(final @Nullable ZonedDateTime purchaseDatePromised, final OrgId orgId)
as discussed, keeping it as it is.

2021-03-26 09:31 UTC, adi-stefan commented on backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/order/impl/CreatePurchaseCandidatesService.java
> +	private Quantity getQuantity(final JsonPurchaseCandidateCreateItem request)
moved.

2021-03-26 09:32 UTC, adi-stefan commented on backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/order/impl/CreatePurchaseCandidatesService.java
> +		throw MissingResourceException.builder()
changed exception class.

2021-03-26 09:32 UTC, adi-stefan commented on backend/de.metas.business.rest-api-impl/src/main/java/de/metas/rest_api/order/impl/CreatePurchaseCandidatesService.java
> +		throw MissingResourceException.builder()
changed exception class.

2021-03-26 09:32 UTC, adi-stefan commented on backend/de.metas.business/src/main/java/de/metas/uom/IUOMDAO.java
> +	I_C_UOM getByProductID(ProductId productId);
dropped like it's hot.

2021-03-26 09:32 UTC, adi-stefan commented on backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/PurchaseCandidateSource.java
> +	MaterialDisposition("MD"),
changed to use constants

2021-03-26 09:32 UTC, adi-stefan commented on backend/de.metas.purchasecandidate.base/src/main/java/de/metas/purchasecandidate/purchaseordercreation/PurchaseOrderPricingInfo.java
> +	@NonNull BigDecimal discount;
removed.

2021-03-26 09:33 UTC, adi-stefan commented on backend/de.metas.swat/de.metas.swat.base/src/main/java/de/metas/modelvalidator/M_Warehouse.java
> +		final I_C_BPartner_Location bpLocation = bpartnerDAO.getBPartnerLocationById(BPartnerLocationId.ofRepoIdOrNull(warehouse.getC_BPartner_ID(),warehouse.getC_BPartner_Location_ID()));
refactored to account for potential null locationId.

2021-03-26 09:33 UTC, adi-stefan commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/sales/purchasePlanning/view/PurchaseRowsSaver.java
> +			qtyToPurchaseRemainingOfGroup.toZero();
yeh, cleaned up.

2021-03-26 09:33 UTC, adi-stefan commented on misc/de-metas-common/de-metas-common-rest_api/src/main/java/de/metas/rest_api/order/JsonWorkPackage.java
> +public class JsonWorkPackage
dropped.

2021-03-26 09:34 UTC, adi-stefan commented on backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/createPurchaseCandidate.feature
> +  Scenario: create a purchase candidate
removed.

2021-03-26 09:57 UTC, metas-ts approved these changes

2021-03-26 09:57 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/uom/IUOMDAO.java
> +import de.metas.product.ProductId;
ok, now pls also remove this little critter

2021-03-26 09:57 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/uom/impl/UOMDAO.java
> +import de.metas.product.ProductId;
here as well, pls clean up the unused imports

2021-03-29 05:42 UTC, merged