Get BPartners from shopware
metasfresh/metasfresh pull request #10911
Opened 2021-03-30 18:26 UTC by cif-ps

Upgraded shopware bpartner route to consume MF API V2

refs: https://github.com/metasfresh/metasfresh/issues/10909

2021-03-30 20:00 UTC, metas-ts requested changes
please check my comments and requests

2021-03-31 05:00 UTC, cif-ps commented on backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5584270_sys_gh10909_Add_shopware_identifier_json_path.sql
> +
fixed

2021-03-31 05:03 UTC, cif-ps commented on misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/api/model/order/JsonOrderCustomer.java
> +
Fixed, but just FYI regarding this, I noticed that sometimes we receive null in the customerId from the order.

2021-03-31 05:04 UTC, cif-ps commented on misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/main/java/de/metas/camel/externalsystems/shopware6/processor/BPartnerUpsertRequestProducer.java
> +				System.out.println(orderAddressWithCustomId);
fixed

2021-03-31 05:15 UTC, cif-ps commented on misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-shopware6/src/test/resources/de/metas/camel/externalsystems/shopware6/CamelUpsertBPartnerCompositeRequest.json
> +                  "activeSet": false,
fixed

2021-03-31 05:16 UTC, cif-ps commented on misc/de-metas-common/de-metas-common-bpartner/src/main/java/de/metas/common/bpartner/v2/request/JsonRequestLocationUpsertItem.java
>  					+ "If a new location is created and the request's location has no different identifier, then this identifier is stored within the newly created lcoation.") //
fixed

2021-03-31 05:20 UTC, cif-ps commented on backend/de.metas.business/src/main/java/de/metas/bpartner/composite/BPartner.java
> +	private Boolean isIdentifiedByExternalReference;
fixed

2021-03-31 05:24 UTC, cif-ps commented on backend/de.metas.business/src/main/java/de/metas/bpartner/composite/BPartnerComposite.java
> +		final boolean hasLookupKey = bpartner.getIsIdentifiedByExternalReference()
It's referring to de.metas.common.bpartner.v2.request.JsonRequestBPartnerUpsertItem#bpartnerIdentifier as you mentioned. I removed JsonRequestComposite#bPartnerReferenceCreateRequest in v2.

2021-03-31 05:31 UTC, cif-ps commented on backend/de.metas.business.rest-api-impl/src/test/resources/de/metas/rest_api/v2/bpartner/bpartnercomposite/JsonRetrieverServiceTest.snap
> -de.metas.rest_api.bpartner.impl.v2.bpartnercomposite.JsonRetrieverServiceTest.retrieveBPartnerComposite_byBPartnerCompositeLookupKeys=[
By mistake, added it back.

2021-03-31 07:11 UTC, metas-ts approved these changes

2021-03-31 07:11 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/bpartner/composite/BPartner.java
> +	 * It's identifier is an external reference that is included in the BPartnerComposite instance which holds this BPartner.
```suggestion
	 * It's identifier is an external reference that is provided outside of this bpartner's composite.
```

2021-03-31 07:16 UTC, merged