Smothen connecting to shopware
metasfresh/metasfresh pull request #11576
Opened 2021-08-03 17:49 UTC by fp-ps

2021-08-17 14:04 UTC, metas-ts requested changes

2021-08-18 12:41 UTC, cp-ps commented on backend/de.metas.adempiere.adempiere/serverRoot/de.metas.adempiere.adempiere.serverRoot.base/src/main/java/de/metas/adempiere/scheduler/SchedulerServiceImpl.java
> +		}
yep, right, def on board with that 👍

2021-08-20 05:04 UTC, metas-ts requested changes

2021-08-20 06:09 UTC, metas-ts approved these changes
will integrate after successful build

2021-08-20 06:47 UTC, merged