Setting clearance in mobileui
metasfresh/metasfresh pull request #12565
Opened 2022-02-19 23:41 UTC by siemiatj

2022-02-20 09:28 UTC, siemiatj commented
@teosarca once the status is selected, `allowedClearanceStatuses` returns a list without this status. So when user changes it, we should re-fetch the statuses ?

![rENfqoBxhy](https://user-images.githubusercontent.com/513460/154836411-a2468578-c3cb-43c9-8ce0-a35b52ddfb56.gif)


https://recordit.co/rENfqoBxhy

2022-02-20 09:31 UTC, teosarca commented
@siemiatj  don't u have the current status in handlingUnits info?

2022-02-21 07:22 UTC, teosarca commented on misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/components/ClearanceDialog.jsx
> +              <button className="button is-success" onClick={onDialogYes}>
the OK button shall be danger.... but it's actually changing things.

2022-02-21 08:13 UTC, teosarca commented on misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/api.js
> +  if (clearanceStatus) {
what's the reason for not having a clearanceStatus?

2022-02-21 08:17 UTC, teosarca requested changes
check my comments

2022-02-21 08:17 UTC, teosarca commented on misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/api.js
> +  if (clearanceNote) {
IMHO in this case u can send null.

2022-02-21 08:17 UTC, teosarca commented on misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/components/HUInfoComponent.jsx
> +        </tr>
Q: don't we need to show the clearance note if any?

2022-02-21 16:17 UTC, teosarca commented on misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/actionTypes.js
> +export const CHANGE_CLEARANCE_STATUS = 'hiManager/CHANGE_CLEARANCE_STATUS';
`huManager` (not hi...)

2022-02-21 16:19 UTC, teosarca commented on misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/api.js
> +  if (clearanceStatus) {
> If it didn't change or user only added clearanceNote, should we send it anyway ?

Nop, a clearanceNote makes no sense without a status.
The `note` is the explanation of the `status`.

e.g. Status:Quarantine, Note: A bird took a dump on it

2022-02-21 16:22 UTC, teosarca commented on misc/services/mobile-webui/mobile-webui-frontend/src/apps/huManager/i18n/de.json
> +  "clearanceStatus": "Clearance Status",
we need trl for this too

2022-02-22 00:14 UTC, siemiatj commented
![aYULIb75Wh](https://user-images.githubusercontent.com/513460/155041114-1e5aeee6-00f4-4d81-a683-454d36f10250.gif)

2022-02-22 06:14 UTC, teosarca commented
@siemiatj  one thing I remarked on ur screenshot: pls keep the `Scan again` button last.

2022-02-22 17:07 UTC, merged