Intensive care uat age range
metasfresh/metasfresh pull request #12632
Opened 2022-03-08 19:20 UTC by metas-rc

https://github.com/metasfresh/metasfresh/issues/12570

2022-03-09 06:07 UTC, metas-ts requested changes
..generally, please annotable new parameters (or existing ones that you find along the way) with `@NonNull` or `@Nullable` to reduce the fear of NPEs

2022-03-09 06:07 UTC, metas-ts commented on backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/age/AgeAttributesService.java
> +	public List<Object> getSuitableValues(final Set<BPartnerId> bPartnerIds, final Set<ProductId> productIds, final Object attributeValue)
LE: maybe reaname the method toExtractMatchingValues? might be misleading..i'm not sure what the method does..but "get" makes it sound more trivial than it is..

2022-03-09 06:07 UTC, metas-ts commented on backend/de.metas.handlingunits.base/src/main/java/de/metas/storage/spi/hu/impl/HUStorageQuery.java
> +			final List<Object> ageValues = ageAttributesService.getSuitableValues(getBPartnerIds(), getProductIds(), attributeValue);
```suggestion
			// "explode" the age-attribute value to a range, using before- and after-intervals from the masterdata
			final List<Object> ageValues = ageAttributesService.getSuitableValues(getBPartnerIds(), getProductIds(), attributeValue);
```

2022-03-09 06:11 UTC, metas-ts commented
Later edit:
please also provide a field description to make the fields better understandable. I think to understand what it's about, the fieldname is not enough. Please also take into account the infos you gave to kay for him to come up with the field name, and also the infos from the issue's requirements.

2022-03-09 06:16 UTC, metas-ts commented
Yes later edit:
I couldn'T find the code for for the "picking profile (v2) config to consider attributes"..
i'm not really sure what it does..i suspect that when i know, maybe i will suggest to drop it, or ask for a clearer field name and maybe also a field-sescription, to reduce FUD

2022-03-10 13:45 UTC, metas-rc commented on backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/age/AgeAttributesService.java
> +		for (final ProductId productId : productIds) // #12570 there should be only one product here. Not sure how to decide which are the time ranges if there are more
done

2022-03-10 13:46 UTC, metas-rc commented on backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/age/AgeAttributesService.java
> +			final int productBefore = product.getPicking_AgeTolerance_BeforeMonths();
refactored

2022-03-10 13:59 UTC, metas-rc commented on backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/age/AgeAttributesService.java
> +		final int minimumValue = Integer.parseInt(attributeValue.toString()) - pickingAgeTolerance_BeforeMonths;
done

2022-03-10 16:39 UTC, metas-rc commented on backend/de.metas.handlingunits.base/src/main/java/de/metas/handlingunits/age/AgeAttributesService.java
> +	public List<Object> getSuitableValues(final Set<BPartnerId> bPartnerIds, final Set<ProductId> productIds, final Object attributeValue)
done

2022-03-10 20:09 UTC, metas-ts approved these changes

2022-03-11 10:39 UTC, merged