Differing Adresses lead to wrong bp-location display on metasfresh documents
metasfresh/metasfresh pull request #12762
Opened 2022-04-04 16:19 UTC by fp-ps

2022-04-04 19:25 UTC, metas-ts commented
@fp-ps please fix the fained tests (probably all not expecting "ephemeral" in the snapshot file)

2022-04-04 19:33 UTC, metas-ts requested changes
please propose an english and german name&description for ephemeral
for name I would say 🗣️ 
- DE Einmalanschrift
- EN One-time-address

2022-04-05 05:38 UTC, fp-ps commented on backend/de.metas.business/src/main/java/de/metas/bpartner/composite/BPartnerLocation.java
> +		this.ephemeral = ephemeral != null ? ephemeral : false;
changed as suggested

2022-04-07 19:11 UTC, metas-ts approved these changes

2022-04-07 19:12 UTC, merged