Fix BankAccount SwiftCode
metasfresh/metasfresh pull request #12834
Opened 2022-04-18 04:03 UTC by riadmen

https://github.com/metasfresh/metasfresh/issues/12817

2022-04-18 16:10 UTC, cristinamghita reviewed
Check my comments

2022-04-18 16:10 UTC, cristinamghita commented on backend/de.metas.business/src/main/java-legacy/org/compiere/model/MPayment.java
>  				}
I don;t understand this.

2022-04-18 16:10 UTC, cristinamghita commented on backend/de.metas.business/src/main/java/de/metas/bpartner/impexp/BPartnerBankAccountImportHelper.java
> +			bankAccount.setSwiftCode(importRecord.getSwiftCode());
Put a name as well, please.
You can still use swift code as a name or generate a combination.

2022-04-19 05:35 UTC, metas-ts requested changes

2022-04-19 05:35 UTC, metas-ts commented on backend/de.metas.payment.revolut/src/main/java/de/metas/payment/revolut/model/RevolutExportCSVColumn.java
> -	BIC("BIC"),
AFAIU
- BIC is the name of the column in the revolut standard.
- BIC is practically the same as switftcode

=> therefore, please leave the name as BIC, at least in the csv output file

2022-04-27 04:47 UTC, metas-ts approved these changes

2022-04-29 13:13 UTC, merged