Leich und Mehl III
metasfresh/metasfresh pull request #13315
Opened 2022-07-21 14:19 UTC by fp-ps

2022-07-22 13:02 UTC, metas-ts requested changes

2022-07-26 07:32 UTC, fp-ps commented on backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/process/IADPInstanceDAO.java
> +	PInstanceId createPInstanceId(@NonNull AdProcessId adProcessId);
removed, as it was not needed anymore

2022-07-26 07:34 UTC, fp-ps commented on backend/de.metas.externalsystem/src/main/java/de/metas/externalsystem/export/pporder/PP_Order_SyncTo_ExternalSystem.java
> +			getExportPPOrderToExternalSystem().exportToExternalSystem(externalSystemChildConfigId, ppOrderRecordRef, pInstanceId);
- process limited to work with exactly 1 PP_Order
- `getPinstanceId()` used instead of creating a new `pInstanceId` record

2022-07-26 07:41 UTC, fp-ps commented on misc/services/camel/de-metas-camel-externalsystems/de-metas-camel-leichundmehl/README.md
> +|metasfresh-json response|metasfresh| Obs |
it should be renamed to `note` to mention addition info for the field in question

2022-08-08 13:47 UTC, metas-ts approved these changes

2022-08-09 05:46 UTC, merged