Fix SEPA for QR
metasfresh/metasfresh pull request #13691
Opened 2022-09-29 07:10 UTC by cristinamghita

2022-09-29 08:04 UTC, metas-ts requested changes

2022-09-29 08:04 UTC, metas-ts commented on backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
> +					othr.setId(iban.replaceAll(" ", ""));
i think iban might be `null` at this place

2022-09-29 08:04 UTC, metas-ts commented on backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
> +		if (bPBankAccount.isEsrAccount() && !Check.isEmpty(line.getStructuredRemittanceInfo(), true) && bPBankAccount.getQR_IBAN() == null)
```suggestion
		if (bPBankAccount.isEsrAccount() && !Check.isEmpty(line.getStructuredRemittanceInfo(), true) && Check.isBlank(bPBankAccount.getQR_IBAN()))
```

2022-09-29 08:04 UTC, metas-ts commented on backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
> +		if(reference!=null && reference.length() != 27)
i think if reference is null we get an NPE further down

2022-09-29 10:39 UTC, metas-ts requested changes

2022-09-29 10:39 UTC, metas-ts commented on backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
> +					if (!Check.isEmpty(otherAccountIdentification, true))
```suggestion
					if (Check.isNotBlank(otherAccountIdentification))
```

2022-09-29 10:39 UTC, metas-ts commented on backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
>  				{
i think we don't need these branckets, or am i missing sth?

2022-09-29 10:39 UTC, metas-ts commented on backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
> +		if (bPBankAccount.isEsrAccount() && !Check.isEmpty(line.getStructuredRemittanceInfo(), true) && Check.isBlank(bPBankAccount.getQR_IBAN()))
```suggestion
		if (bPBankAccount.isEsrAccount() && Check.isNotBlank(line.getStructuredRemittanceInfo()) && Check.isBlank(bPBankAccount.getQR_IBAN()))
```

2022-09-29 10:39 UTC, metas-ts commented on backend/de.metas.payment.sepa/base/src/main/java/de/metas/payment/sepa/sepamarshaller/impl/SEPAVendorCreditTransferMarshaler_Pain_001_001_03_CH_02.java
> +		if(reference!=null && reference.length() != 27)
wdyt about 
```java
	static boolean isInvalidQRReference(@NonNull final String reference)
	{
		if(reference.length() != 27)
```
?

2022-09-29 14:56 UTC, merged

2022-09-30 17:28 UTC, adi-stefan commented
merged to master in https://github.com/metasfresh/metasfresh/commit/1a5447da0089f0037a3e24628e6bec1cfc21b8f7