15694 fenster bestellanforderung iteration 2
metasfresh/metasfresh pull request #15695
Opened 2023-06-25 23:41 UTC by chemsnouioua

#15694

2023-06-29 12:40 UTC, teosarca commented on backend/de.metas.business/src/main/java/de/metas/requisition/callout/M_Requisition.java
> +	}
@mrie04  u could write this as follows:
```java
WarehouseId.optionalOfRepoId(requisition.getM_Warehouse_ID())
.map(warehouseDAO::getById)
.ifPresent(warehouse -> requisition.setWarehouse_Location_ID(warehouse.getC_BPartner_Location_ID()) );
```

also pls extract warehouseDAO as a class field

2023-06-29 12:41 UTC, teosarca commented on backend/de.metas.business/src/main/java/de/metas/requisition/interceptor/M_RequisitionLine.java
> +		calculateTotalLines(line);
hmmm, this won't work nice in case multiple lines are updated in the same transaction 
or in case a new line is created
or a line is deleted

2023-06-29 13:34 UTC, teosarca commented on backend/de.metas.business/src/main/java/de/metas/requisition/interceptor/M_RequisitionLine.java
> +		calculateTotalLines(line);
pls consider using org.adempiere.ad.trx.api.ITrxManager#accumulateAndProcessAfterCommit

2023-06-29 13:36 UTC, teosarca commented on backend/de.metas.business/src/main/java/de/metas/requisition/interceptor/M_RequisitionLine.java
> +		calculateTotalLines(line);
e.g.
![image](https://github.com/metasfresh/metasfresh/assets/1244701/47b0db03-f182-4b5c-a7b9-38d430254594)

2023-06-30 06:52 UTC, cristinamghita requested changes
check my comments

2023-06-30 06:52 UTC, cristinamghita commented on backend/de.metas.business/src/main/java/de/metas/requisition/RequisitionRepository.java
>  				.delete();
extract service as a class field

2023-06-30 06:52 UTC, cristinamghita commented on backend/de.metas.business/src/main/java/de/metas/requisition/RequisitionService.java
> +		InterfaceWrapperHelper.save(requisition);
extracting saving requisition to repository

2023-06-30 07:32 UTC, cristinamghita approved these changes
lgtm

2023-06-30 07:36 UTC, merged