Use harvest calendar for modular and interim payment contracts
metasfresh/metasfresh pull request #16538
Opened 2023-10-25 11:47 UTC by dm-ps

refs: https://github.com/metasfresh/metasfresh/issues/16534

2023-10-25 16:22 UTC, adi-stefan requested changes
minor thing, please also check failing cucumber

2023-10-25 16:22 UTC, adi-stefan commented on backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateTransitionQuery.java
> +	@NonNull FlatrateTransition templateFlatrateTransition;
Please keep this as a POJO, avoid aggregating objects.

2023-10-25 16:23 UTC, adi-stefan requested changes
lgtm

2023-10-26 05:44 UTC, adi-stefan approved these changes

2023-10-26 06:23 UTC, merged

2023-10-26 09:02 UTC, teosarca commented on backend/de.metas.contracts/src/main/java/de/metas/contracts/impl/FlatrateTransition.java
> +	@NonNull Integer termDuration;
@dm-ps cc @adi-stefan  next time pls consider using Duration instead