Match invoice by esr reference and allow batch processing - part 2
metasfresh/metasfresh pull request #16571
Opened 2023-10-31 12:39 UTC by cristinamghita

Solving remaining issues from https://github.com/metasfresh/metasfresh/pull/16569

2023-11-02 14:59 UTC, metas-ts requested changes

2023-11-02 15:17 UTC, metas-ts commented on backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bankStatement/camt.53.001.04-Import.feature
>  #      | Identifier  | C_BPartner_ID.Identifier | C_Currency.ISO_Code | OPT.AccountNo | OPT.C_Bank_ID.Identifier |
```suggestion
```

2023-11-02 15:20 UTC, metas-ts commented on backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/bankStatement/camt.53.001.04-Import.feature
> +      | inv_1_S0337_100 | bpartner_1_S0337         | Ausgangsrechnung        | 2022-05-11   | Spot                     | true    | EUR                 | 511004_S0337_100 |
the invoice is in eur but the bankstatement-line is in CHF..so i guess somethingneeds to be wrong with the amounts-matching

2023-11-03 13:35 UTC, cristinamghita commented on backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/bankStatement/C_BankStatementLine_StepDef.java
> +			softly.assertThat(invoiceRecord).as("C_BankStatementLine_ID.Identifier=%s - C_Invoice record %s for identifier=%s ", bslIdentifier, invoiceRecord.getC_Invoice_ID(),invoiceIdentifier).isNotNull();
If the invoiceIdentifier is found, I don't think it can fail. invoiceRecord  shall not be null in that case.
Or you wrote the test wrong.

2023-11-07 12:45 UTC, teosarca commented on backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/bankStatement/C_BankStatementLine_StepDef.java
> +			softly.assertThat(invoiceRecord).as("C_BankStatementLine_ID.Identifier=%s - C_Invoice record %s for identifier=%s ", bslIdentifier, invoiceRecord.getC_Invoice_ID(),invoiceIdentifier).isNotNull();
agree with Tobi 
pls avoid calling getC_Invoice_ID() because invoiceRecord can be null
that's what are u checking!

2023-11-07 12:55 UTC, cristinamghita commented on backend/de.metas.cucumber/src/test/java/de/metas/cucumber/stepdefs/bankStatement/C_BankStatementLine_StepDef.java
> +			softly.assertThat(invoiceRecord).as("C_BankStatementLine_ID.Identifier=%s - C_Invoice record %s for identifier=%s ", bslIdentifier, invoiceRecord.getC_Invoice_ID(),invoiceIdentifier).isNotNull();
Got it know! Fixed it!

2023-11-08 16:16 UTC, teosarca approved these changes
lgtm
cc @metas-ts

2023-11-09 07:52 UTC, merged