Implement matching between the attributes of order lines and product proposal rows
metasfresh/metasfresh pull request #16589
Opened 2023-11-02 20:02 UTC by metas-rc

2023-11-03 07:37 UTC, adi-stefan requested changes
see my comments

2023-11-03 07:37 UTC, adi-stefan commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/service/Order.java
>  	public Optional<OrderLine> getFirstMatchingOrderLine(
we should remove this, no?

2023-11-03 07:37 UTC, adi-stefan commented on frontend/yarn.lock
> +"@babel/code-frame@^7.22.13":
please revert changes to this file

2023-11-03 08:20 UTC, metas-rc commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/service/Order.java
>  	public Optional<OrderLine> getFirstMatchingOrderLine(
yes. Removed

2023-11-03 08:21 UTC, metas-rc commented on frontend/yarn.lock
> +"@babel/code-frame@^7.22.13":
by mistake. revert done

2023-11-03 08:23 UTC, adi-stefan approved these changes

2023-11-03 09:25 UTC, merged

2023-11-06 12:22 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsData.java
> +				.collect(ImmutableList.toImmutableList());
why `List` and not `Set`?

2023-11-06 12:26 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/model/ProductsProposalRowsLoader.java
> +		return rowBuilder
i think u can be fluent here....

2023-11-06 12:30 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
> +	public Map<ProductPriceId, OrderLine> findBestMatchesForOrderLineFromProductPrices(final Order order, final List<I_M_ProductPrice> productPrices)
mark `order` param as `@Nullable`

2023-11-06 12:36 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
> +	public AttributeSetInstanceId extractProductASI(final I_M_ProductPrice record)
static, private?

2023-11-06 12:53 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
> +			return 0;
why?

2023-11-06 12:53 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
> +			return 1;
why?

2023-11-06 12:54 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
> +		final AttributesKey olAk = getAttributesKeyFor(olAsiId);
IMHO `olAk` can be a parameter instead of `olAsiId`.... ok, with a decent name

2023-11-06 13:22 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
> +		final AttributesKey attributesKey = olAk.getIntersection(ppAk);
commonKeys

2023-11-06 13:23 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/order/products_proposal/service/OrderProductProposalsService.java
> +	private int getNumberOfMatchingAttributes(final AttributeSetInstanceId olAsiId, final AttributeSetInstanceId productPriceAsiId)
getMatchingScore