Intensive_care_uat desadv qty in invoice uom
metasfresh/metasfresh pull request #16770
Opened 2023-11-22 11:18 UTC by dm-ps

2023-11-22 15:14 UTC, metas-ts requested changes
the code LGTM as far as i understood it - besides that one div-by-0 concern.
 
What i'm not sure about from the (test-)code and documented dev-test though
is whether it actually work with >1 LUs with those 3 scenarios that were outlined in the TC.
But if you are optimistic in this regard, let's verify it in the UAT-docu and save the time in the dev-phase.

2023-11-22 15:34 UTC, dm-ps commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/handlingunits/process/WEBUI_M_ReceiptSchedule_ReceiveHUs_UsingConfig.java
> +			case PARAM_QtyCUsPerTU:
verified on local, added to dev docu

2023-11-22 16:10 UTC, dm-ps commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/pporder/process/WEBUI_PP_Order_Receipt.java
> +	@Param(parameterName = PackingInfoProcessParams.PARAM_QtyCUsPerTU, mandatory = true)
verified on local, added to dev docu

2023-11-22 16:23 UTC, dm-ps commented on backend/de.metas.business/src/main/java/de/metas/quantity/StockQtyAndUOMQty.java
> +							.divide(stockQty.toBigDecimal(), uomPrecision.getRoundingMode());
in such case, IMHO, we shall return 0, pushed the change

2023-11-22 17:30 UTC, dm-ps commented
> the code LGTM as far as i understood it - besides that one div-by-0 concern.
> 
> What i'm not sure about from the (test-)code and documented dev-test though is whether it actually work with >1 LUs with those 3 scenarios that were outlined in the TC. But if you are optimistic in this regard, let's verify it in the UAT-docu and save the time in the dev-phase.

Added scenario `2 LUs` in dev docu for situation when >1LUs

2023-11-23 06:00 UTC, metas-ts approved these changes

2023-11-23 06:48 UTC, merged