Make sure only active Sales Order Candidates are processed
metasfresh/metasfresh pull request #17220
Opened 2024-01-31 17:35 UTC by riadmen

https://github.com/metasfresh/metasfresh/issues/17219

2024-02-01 07:19 UTC, mrie04 requested changes
pls check my suggestions

2024-02-01 07:19 UTC, mrie04 commented on backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/process/C_OLCandEnqueueForSalesOrderCreation.java
> +				.addEqualsFilter(I_C_OLCand.COLUMNNAME_IsActive, true)
```suggestion
.addOnlyActiveRecordsFilter()
```

2024-02-01 07:19 UTC, mrie04 commented on backend/de.metas.salescandidate.base/src/main/java/de/metas/ordercandidate/process/C_OLCandEnqueueForSalesOrderCreation.java
> +			throw new AdempiereException(msg).markAsUserValidationError();
```suggestion
throw new AdempiereException(MSG_OL_CANDENQUEUE_FOR_SALES_ORDER_CREATION_NO_VALID_RECORD_SELECTED).markAsUserValidationError();
```

2024-02-01 09:05 UTC, mrie04 approved these changes
lgtm

2024-02-01 09:44 UTC, merged

2024-02-02 14:22 UTC, metas-ts commented
@MergifyIO copy release