Implement HL and Protein feature
metasfresh/metasfresh pull request #18077
Opened 2024-05-27 08:41 UTC by cristinamghita

2024-05-27 15:18 UTC, teosarca commented on backend/de.metas.business/src/main/java/de/metas/document/dimension/Dimension.java
> +				.userElement1Id(CoalesceUtil.firstGreaterThanZero(this.userElement1Id, other.userElement1Id))
why not coalese not null?

2024-05-27 15:19 UTC, teosarca commented on backend/de.metas.adempiere.adempiere/base/src/main/java/de/metas/acct/api/AccountDimension.java
> +		return NumberUtils.asBigDecimal(getSegmentValue(AcctSegmentType.UserElementNumber2), BigDecimal.ZERO);
why not returning BigDecimal or null ?

2024-05-27 15:21 UTC, teosarca commented on backend/de.metas.business/src/main/java/de/metas/document/dimension/Dimension.java
> +				.userElementNumber2(CollectionUtils.singleElementOrDefault(userElementNumber2, BigDecimal.ZERO))
why not singleElementOrNull ?
(talking about UserElementNumber1 and UserElementNumber2)

2024-05-27 15:22 UTC, teosarca commented on backend/de.metas.business/src/main/java/de/metas/order/IOrderLineBL.java
> +	PriceListVersionId getPriceListVersion(I_C_OrderLine orderLine);
pls rename it to getPriceListVersionId

2024-05-27 15:22 UTC, teosarca commented on backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
> +	public PriceListVersionId getPriceListVersion(final I_C_Order order)
pls rename it to getPriceListVersionId

2024-05-27 15:23 UTC, teosarca commented on backend/de.metas.business/src/main/java/de/metas/pricing/service/ProductPrices.java
> +	final static private IProductBL productBL = Services.get(IProductBL.class);
pls avoid static services!

2024-05-27 17:53 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentRow.java
> +				case FIELD_UserElementNumber1 -> builder.userElementNumber1(request.getValueAsBigDecimal(BigDecimal.ZERO));
why can't be null?

2024-05-27 17:54 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentRow.java
> +				&& userElementNumber1.signum() != 0
why checking to be non-zero?

2024-05-27 17:54 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/split_shipment/SplitShipmentRow.java
> +				case FIELD_UserElementNumber1 -> builder.userElementNumber1(request.getValueAsBigDecimal(BigDecimal.ZERO));
imho zero might be a valid value. we have to support nulls

2024-05-27 17:56 UTC, teosarca commented on backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/process/ModCntr_Specific_Delete_Price.java
> +		if (!contractPrice.isScalePrice() && NumberUtils.isZeroOrNull(contractPrice.minValue()))
contractPrice.isScalePrice might be null => NPE when unboxing

2024-05-27 17:57 UTC, teosarca requested changes
check my QA commits & also check my comments

2024-05-28 15:20 UTC, teosarca commented on backend/de.metas.contracts/src/main/java/de/metas/contracts/modular/computing/purchasecontract/averageonshippedqty/AbstractUENShipmentLineLog.java
> +				.userElementNumber1(inOutLineRecord.getUserElementNumber1())
why not using InterfaceWrapperHelper.getValueAsBigDecimalOrNull?

2024-05-29 13:31 UTC, teosarca commented on backend/de.metas.business/src/main/java/de/metas/document/dimension/Dimension.java
> +				.userElement1Id(CoalesceUtil.firstGreaterThanZero(this.userElement1Id, other.userElement1Id))
i think this shall not be here... u already have it at line 108

2024-05-29 13:35 UTC, cristinamghita commented on backend/de.metas.business/src/test/java/de/metas/document/dimension/DimensionTest.java
> +					.build();
Nothing
Fixed

2024-05-29 13:38 UTC, teosarca commented on backend/de.metas.business/src/test/java/de/metas/document/dimension/InvoiceLineDimensionFactoryTest.java
> +				.userElementNumber1(BigDecimal.ZERO)
nop! those shall be null!

2024-05-29 13:38 UTC, teosarca commented on backend/de.metas.business/src/test/java/de/metas/document/dimension/InvoiceLineDimensionFactoryTest.java
> +				.userElementNumber1(BigDecimal.ZERO)
fix ur de.metas.document.dimension.InvoiceLineDimensionFactory#getFromRecord implementation

2024-05-29 13:41 UTC, teosarca commented on backend/de.metas.cucumber/src/test/resources/de/metas/cucumber/features/groupInvoiceCandidates.feature
> +@dev:runThisOne
i think u don't need this anymore?

2024-05-29 13:42 UTC, teosarca commented on backend/de.metas.swat/de.metas.swat.base/src/test/java/de/metas/invoicecandidate/document/dimension/InvoiceCandidateDimensionFactoryTest.java
> +				.userElementNumber2(BigDecimal.ZERO)
i think it shall be null!

2024-05-29 13:44 UTC, teosarca requested changes
check my comments

2024-05-29 13:45 UTC, cristinamghita commented on backend/de.metas.contracts/src/main/sql/postgresql/ddl/views/ModCntr_UseElementNumber_V.sql
> +CREATE OR REPLACE VIEW ModCntr_UseElementNumber_V AS
we need for reports

2024-05-29 13:53 UTC, teosarca commented on backend/de.metas.business/src/test/java/de/metas/document/dimension/InvoiceLineDimensionFactoryTest.java
> +import java.math.BigDecimal;
unnecessary import

2024-05-29 14:38 UTC, teosarca approved these changes

2024-05-29 18:24 UTC, merged