User Mail CC  (Proto)
metasfresh/metasfresh pull request #18953
Opened 2024-09-24 21:44 UTC by metas-rc

2024-09-26 04:25 UTC, metas-ts approved these changes
i approved, but please add that field-descripton before integrating.  AD_User is broad in the functional sense. and this field might cause FUD, unless it'S clear that:
- it's just about email (not e.g. notification)
- it's always about **Cc** if the current user **receives** a mail

2024-09-26 04:25 UTC, metas-ts commented on backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5734590_A_User_CC.sql
> +INSERT INTO AD_Element (AD_Client_ID,AD_Element_ID,AD_Org_ID,ColumnName,Created,CreatedBy,EntityType,IsActive,Name,PrintName,Updated,UpdatedBy) VALUES (0,583286,0,'CC_User_ID',TO_TIMESTAMP('2024-09-2
please add a description indicating that this uses is always getting a mail as Cc when the user in question receives a mail

2024-09-26 06:23 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/mail/MailRestController.java
> +		final EMailAddress cc = toList.size()>1 ? toList.get(1) : null;
what happens with toList[2], toList[3] etc?

2024-09-26 06:25 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/mail/MailRestController.java
> +		final EMailAddress cc = toList.size()>1 ? toList.get(1) : null;
checking at line 260, i see
```java
toList.stream().skip(1).forEach(email::addTo)
```

isn't there an overlap between `to`s and cc?

2024-09-26 06:27 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/mail/MailRestController.java
> +		final EMailAddress cc = toList.size()>1 ? toList.get(1) : null;
I suggest to 
* either implement support for CC to webui mail (frontend too)
* either accept that Webui Mail does not support CC yet (is that in the requirements?)

2024-09-26 06:27 UTC, teosarca requested changes
pls check my comments

2024-09-27 15:01 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/mail/MailRestController.java
> +		final List<LookupValue> lookupValues = ImmutableList.of(to, cc);
NPE when cc is null?

2024-09-27 16:36 UTC, teosarca approved these changes

2024-09-27 16:37 UTC, merged