DocOutbound - Mass PDF: Use Window Record Sorting for PDF
metasfresh/metasfresh pull request #19339
Opened 2024-11-12 15:16 UTC by dm-ps

refs: https://github.com/metasfresh/metasfresh/issues/19337

2024-11-12 15:32 UTC, teosarca commented on backend/de.metas.ui.web.base/src/main/java/de/metas/ui/web/window/datatypes/DocumentIdsSelection.java
> +	public <ID extends RepoIdAware> ImmutableList<ID> toListIds(@NonNull final Function<Integer, ID> idMapper)
why not calling it `toImmutableList` too?

2024-11-12 15:36 UTC, teosarca commented on backend/de.metas.swat/de.metas.swat.webui/src/main/java/de/metas/archive/process/MassConcatenateOutboundPdfs.java
> +				.sorted(Comparator.comparingInt(o -> orderMap.getOrDefault(DocOutboundLogId.ofRepoId(o.getC_Doc_Outbound_Log_ID()), Integer.MAX_VALUE)))
this kills any streaming performance because we have to accumulate everything in memory in order to make sure it's "sorted"

2024-11-12 15:55 UTC, metas-ts requested changes
I don't think this change will scale if there are many DocOutbound-Records (like 5k).
@teosarca is going to provide a prototype-PR which you can then continue with

2024-11-13 08:11 UTC, metas-ts approved these changes

2024-11-13 09:20 UTC, merged