SQL Process to Create Purchase Candidates from Shipment Schedules
metasfresh/metasfresh pull request #19683
Opened 2024-12-19 12:36 UTC by dm-ps

refs: https://github.com/metasfresh/metasfresh/issues/19682

2025-01-02 08:18 UTC, metas-ts requested changes

2025-01-02 08:18 UTC, metas-ts commented on backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5742260_sys_gh19682_create_purchase_candidates_from_shipment_schedules_function.sql
> +    WHERE ms.processed = 'Y'
why create purchase candidates for shipment-scheds that are already processed? i would have guessed the user rather needs them to purchase supplies for future shipments?

2025-01-02 08:18 UTC, metas-ts commented on backend/de.metas.business/src/main/sql/postgresql/system/20-de.metas.business/5742260_sys_gh19682_create_purchase_candidates_from_shipment_schedules_function.sql
> +                p_m_shipmentschedule_ids = 'all'
usually, by "all", the user means "all records that match the current filter", not all records in existence. 
So I think you need to go via the view-id.

2025-01-02 08:18 UTC, metas-ts commented on backend/de.metas.business/src/main/sql/postgresql/ddl/functions/Create_Purchase_Candidates_From_Shipment_Schedules.sql
> +            WHERE pc.m_shipmentschedule_id = ms.m_shipmentschedule_id
i think what without an idex, this select will become very slow over time

2025-01-23 05:50 UTC, teosarca commented
@dm-ps  is this PR still needed?

2025-01-23 09:27 UTC, metas-ts commented
It's deployed to a UAT-instance, so at any rate it can't be closed without further consolidation

2025-02-27 23:27 UTC, teosarca commented
@dm-ps  @metas-ts  ok, issues are closed, this one is still here... so what shall we do with it?

2025-02-28 06:35 UTC, metas-ts commented
it's obsolete now

2025-02-28 06:35 UTC, closed without merging