#7109 Initial commit.
metasfresh/metasfresh pull request #7118
Opened 2020-08-10 21:38 UTC by dragospodariu96

#7109

2020-08-17 13:03 UTC, metas-ts commented on backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5565000_sys_gh7109AddUpdateOrderAndInvoiceIdProcess.sql
> +INSERT INTO AD_Process (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Process_ID,AllowProcessReRun,Classname,CopyFromProcess,Created,CreatedBy,EntityType,IsActive,IsApplySecuritySettings,IsBetaFunctionality,
make sure the process has an understandable name and description

2020-08-17 13:04 UTC, metas-ts commented on backend/de.metas.adempiere.adempiere/base/src/main/java-gen/org/compiere/model/I_C_Order.java
> +	String COLUMNNAME_AD_InputDataSource_ID = "AD_InputDataSource_ID";
that's OK, but then please remove this stuff from `de.metas.order.model.I_C_Order`

2020-08-17 13:06 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceDAO.java
> +	Map<OrderId, InvoiceId> getInvoiceIdsForOrderIds(final List<OrderId> orderIds);
```suggestion
	Map<OrderId, InvoiceId> getInvoiceIdsForOrderIds(List<OrderId> orderIds);
```

2020-08-17 13:06 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/invoice/service/IInvoiceDAO.java
> +	I_C_Invoice getByOrderId(final OrderId orderId);
```suggestion
	I_C_Invoice getByOrderId(OrderId orderId);
```

2020-08-17 13:12 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/InvoiceDAO.java
> +			orderIdInvoiceIdMap.put(orderId, InvoiceId.ofRepoId(getByOrderId(orderId).getC_Order_ID()));
i think there is no point loading them one-by-one.
you can use IQueryBuilder.addInArrayFilter()

2020-08-17 13:12 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/InvoiceDAO.java
> +		final I_C_Invoice invoice = Services.get(IQueryBL.class)
i think the method is never used. can be removed or made private

2020-08-17 13:14 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/invoice/service/impl/InvoiceDAO.java
> +	public Map<OrderId, InvoiceId> getInvoiceIdsForOrderIds(final List<OrderId> orderIds)
move this method into AbstractInvoiceDAO. Is has no hardcoded SQL-stuff, so we don't need a dedicated `PlainInvoiceDAO.java` implementation

2020-08-17 13:15 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/order/impl/AbstractOrderDAO.java
> +	{
the same comments as in `IInvoiceDAO`

2020-08-17 13:16 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
> +	@Override
why this method in OrderBL?

2020-08-17 13:27 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/payment/api/impl/PaymentBL.java
> +	public String isPaypalOrCreditCardPayment(final I_C_Payment payment, final int paypalDataSourceId, final int creditCardDataSourceId)
this method and it's invocation in `de.metas.banking.process.C_Payment_UpdateOrderAndInvoiceId#doIt` is unneccesary complex. 
Also:
* if it starts with `is` it should return a boolean
* don't return a String constant, but (*if* this method is not removed), an enum

2020-08-23 21:14 UTC, dragospodariu96 commented on backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5564980_sys_gh7109PaymentRuleColumnAddedToCPaymentTable.sql
> +;
This is removed a few lines down.

2020-08-25 06:57 UTC, dragospodariu96 commented on backend/de.metas.business/src/main/java/de/metas/order/impl/AbstractOrderDAO.java
> +	{
made it private

2020-08-25 07:00 UTC, dragospodariu96 commented on backend/de.metas.business/src/main/java/de/metas/order/impl/OrderBL.java
> +	@Override
not used, removed method

2020-08-26 08:46 UTC, metas-ts requested changes

2020-08-26 08:46 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/payment/interceptor/C_Payment.java
> +public class C_Payment
(i wrote this comment after the two that follow in this class)

I understand that this is aiming at completed payments that get their respective invoice from your process.
* I think that your process is the only one to set C_Order_ID and C_Invoice_ID on an already completed payment
* for not-yet-completed payment, we AFAIU have Cristian's code

=> so, rather that have this model interceptor that "incidentally" allocated the payment,
make the allocation explicitly in the PaymentBL-code that also sets the C_Order_ID and C_Invoice_ID

2020-08-26 08:46 UTC, metas-ts commented on backend/de.metas.business/src/main/java/de/metas/payment/interceptor/PaymentModuleInterceptor.java
> +		calloutsRegistry.registerAnnotatedCallout(C_Payment.INSTANCE); // FRESH-348
* C_Payment has no callout methods AFAIU
* Generally, think we should ditch the whole intercheptor; see my comment at C_Payment

2020-08-27 18:12 UTC, dragospodariu96 commented on backend/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5565000_sys_gh7109AddUpdateOrderAndInvoiceIdProcess.sql
> +;
Added description and updated name

2020-08-28 05:47 UTC, metas-ts approved these changes

2020-08-28 11:52 UTC, merged