Create a WidgetWrapper component for fetching data
metasfresh/metasfresh pull request #9992
Opened 2020-09-22 16:09 UTC by siemiatj

Second attempt after doing a thorough manual testing. Related to #9914

2020-09-23 09:02 UTC, petrican requested changes

2020-09-23 09:06 UTC, petrican commented
Looks fine, left some comments. I would request a 2nd functional smoke tests before merging this into master from another developer willing to test this of from Daniela but doubt she is available. Maybe ask Phillip who might be available to test.

2020-09-23 09:32 UTC, siemiatj commented on frontend/src/components/widget/RawWidget.js
> +    let widgetValue = data != null ? data : widgetData[0].value;
Nope. This tests for values not set - `null` and `undefined`. `''` and `0` will still work.

2020-09-23 09:33 UTC, siemiatj commented on frontend/src/containers/WidgetWrapper.js
> +      widgetData = getProcessWidgetData(state, true, layoutId);
It's process's widget data, not widget's process data.

2020-09-23 09:36 UTC, siemiatj commented on frontend/src/components/window/Element.js
> +    const layoutId = `${sectionIndex}_${columnIndex}_${elementGroupIndex}_${elementsLineIndex}_${elementIndex}`;
Yeah but in this case this is the only place we're using it so extracting this to a separate function wouldn't benefit us in any way.

2020-09-24 08:58 UTC, petrican commented
lgtm. Thanks!

2020-09-24 08:58 UTC, petrican approved these changes

2020-09-28 07:30 UTC, merged